"""
Auto-generated by tools/generate_codes.py - DO NOT EDIT MANUALLY.
Regenerate with: python tools/generate_codes.py
"""

from __future__ import annotations
from dicom4ortho.m_dent_oip import AdaImageType, DicomCode, OrthoView


SOURCE_PROVENANCE: dict[str, dict[str, str]] = {
    'DCM_ONTOLOGY': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/ontology/DCM/dcm.owl',
        'sha256': '8692e5420c6db5ceeed53d74055aa2a1a26fc70b72fe5705a3cd9e3c3722512f',
    },
    'CID247': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-247-LateralityLeftRightOnly.json',
        'sha256': 'abe280610e46ca094505dde6ea6ef747bddc1fb5a9ca0e101eb9a5adc51bf714',
        'version': '20190524',
        'date': '2026-06-12',
    },
    'CID4028': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4028-CraniofacialAnatomicRegion.json',
        'sha256': '5b4211525215b66c0d2acd9c4e2d36ad4ccc584fbe5e6e62f7b27f6564bbdd9e',
        'version': '20250908',
        'date': '2026-06-12',
    },
    'CID4061': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4061-HeadAndNeckPrimaryAnatomicStructure.json',
        'sha256': 'e5b020509904861adce19a6ac4c4db30781bf8a7ef323d29f1c57405d108a165',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4062': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4062-VLView.json',
        'sha256': 'dfa77d4a59d52531dc266cae7dd5205afed24ba02ae4ba773b6600e10fa77703',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4063': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4063-VLDentalView.json',
        'sha256': '6d35bd0f0b5852b2aed1de9694559757fa5d26a5e98778f98a4e4f2b3cb0d659',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4064': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4064-VLViewModifier.json',
        'sha256': '8323144db45220f02e60a50f2ecfc99d89dc5dbf07f6def8658a4e8a0180f385',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4065': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4065-VLDentalViewModifier.json',
        'sha256': 'adc8c7104aa85799459b55a420ac1b9100c5d6a98d66a8843a1e2d1679f37a91',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4066': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4066-OrthognathicFunctionalCondition.json',
        'sha256': '3f7c05af5c585f913ca73a6e90f40f5fb42d28bbac1dd3b78f13a6d0bb41a928',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4067': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4067-OrthodonticFindingByInspection.json',
        'sha256': '4e20fcc5a79608c20e83358e6202ba7bce4b3f3ee2415fdb4d0d611ae8fdec6b',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4068': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4068-OrthodonticObservableEntity.json',
        'sha256': 'da1a3895860d40ded8998fc3cb4a6b738103ae15df42ff94c7fad1ee72396c05',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4069': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4069-DentalOcclusion.json',
        'sha256': '1b03c3ffcf7ff40cb4a6bd7fc5a36ac26666e96d26319515162bdb79ada43925',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4070': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4070-OrthodonticTreatmentProgress.json',
        'sha256': '8b22c8133de22b1fa5ce2049fbc1e61a9bb2212a45552fe9cea15d85b39be0b0',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'CID4072': {
        'url': 'ftp://medical.nema.org/medical/dicom/resources/valuesets/fhir/json/ValueSet-dicom-cid-4072-DevicesForThePurposeOfDentalPhotography.json',
        'sha256': 'b5e245905e63576c6c3ba4dcb71d399929a38f958dedbf77458e24f3e25b804e',
        'version': '20250330',
        'date': '2026-06-12',
    },
    'ADA_INTRAORAL_2D': {
        'url': 'https://terminology.open-ortho.org/fhir/sid/ada1100/CodeSystem/intraoral-2d-photographic-scheduled-protocol',
        'sha256': 'dd37fdff2c9dbe8be40d9964f795842940a0a1f2ae64cdc122d148a205dd78c0',
        'version': '2.0.0',
        'date': '2026-07-04',
    },
    'ADA_EXTRAORAL_2D': {
        'url': 'https://terminology.open-ortho.org/fhir/sid/ada1100/CodeSystem/extraoral-2d-photographic-scheduled-protocol',
        'sha256': '9757675a62c07ef29bf02910579b8adc65abac18805ec4dcc1c888a45fa84cf9',
        'version': '2.0.0',
        'date': '2026-07-04',
    },
    'VIEWS': {
        'url': 'https://raw.githubusercontent.com/open-ortho/dent-oip/latest/source/tables/views.csv',
        'sha256': '2580ec0517d9bff7804ff79f1913c9a31667d55741122aa8b4c8bce5ffe36945',
    },
}


FINDING_BY_INSPECTION = DicomCode(
    value='118243007',
    scheme='SCT',
    meaning='Finding by inspection',
)

OBSERVABLE_ENTITY = DicomCode(
    value='363787002',
    scheme='SCT',
    meaning='Observable entity',
)

DENTAL_OCCLUSION = DicomCode(
    value='25272006',
    scheme='SCT',
    meaning='Dental occlusion',
)

DAY = DicomCode(
    value='d',
    scheme='UCUM',
    meaning='days',
)

LATERALITY_BOTH = DicomCode(
    value='B',
    scheme='CS',
    meaning='Both',
)

LATERALITY_LEFT = DicomCode(
    value='L',
    scheme='CS',
    meaning='Left',
)

LATERALITY_RIGHT = DicomCode(
    value='R',
    scheme='CS',
    meaning='Right',
)

LATERALITY_UNPAIRED = DicomCode(
    value='U',
    scheme='CS',
    meaning='Unpaired',
)

ORIENTATION_LEFT = DicomCode(
    value='P^F',
    scheme='CS',
    meaning='Posterior, Foot',
)

ORIENTATION_RIGHT = DicomCode(
    value='A^F',
    scheme='CS',
    meaning='Anterior, Foot',
)

ORIENTATION_SUPINE_HEAD_TO_FEET = DicomCode(
    value='R^P',
    scheme='CS',
    meaning='Right, Posterior',
)

ORIENTATION_PRONE_FEET_TO_HEAD = DicomCode(
    value='R^A',
    scheme='CS',
    meaning='Right, Anterior',
)

ORIENTATION_FRONT = DicomCode(
    value='L^F',
    scheme='CS',
    meaning='Left, Foot',
)

ORIENTATION_BACK = DicomCode(
    value='R^F',
    scheme='CS',
    meaning='Right, Foot',
)

ORIENTATION_SUPINE_FEET_TO_HEAD = DicomCode(
    value='L^P',
    scheme='CS',
    meaning='Left, Posterior',
)

ORIENTATION_PRONE_HEAD_TO_FEET = DicomCode(
    value='L^A',
    scheme='CS',
    meaning='Left, Anterior',
)

RIGHT = DicomCode(
    value='24028007',
    scheme='SCT',
    meaning='Right',
)

LEFT = DicomCode(
    value='7771000',
    scheme='SCT',
    meaning='Left',
)

MOUTH = DicomCode(
    value='123851003',
    scheme='SCT',
    meaning='Mouth',
)

HEAD_NECK = DicomCode(
    value='774007',
    scheme='SCT',
    meaning='Head and Neck',
)

DENTAL_ARCH_MANDIBULAR = DicomCode(
    value='88176008',
    scheme='SCT',
    meaning='Mandibular dental arch',
)

DENTAL_ARCH_MAXILLARY = DicomCode(
    value='39481002',
    scheme='SCT',
    meaning='Maxillary dental arch',
)

STRUCTURE_OF_BUCCAL_SPACE = DicomCode(
    value='261063000',
    scheme='SCT',
    meaning='Buccal space',
)

FRENUM = DicomCode(
    value='7652006',
    scheme='SCT',
    meaning='Frenulum labii',
)

FACE_STRUCTURE = DicomCode(
    value='89545001',
    scheme='SCT',
    meaning='Face',
)

ORAL_CAVITY_STRUCTURE = DicomCode(
    value='74262004',
    scheme='SCT',
    meaning='oral cavity',
)

PROJECTION_FRONTAL = DicomCode(
    value='399033003',
    scheme='SCT',
    meaning='frontal',
)

PROJECTION_LEFT = DicomCode(
    value='399173006',
    scheme='SCT',
    meaning='left lateral',
)

PROJECTION_LEFT_OBLIQUE = DicomCode(
    value='260421001',
    scheme='SCT',
    meaning='left lateral oblique',
)

PROJECTION_RIGHT = DicomCode(
    value='399198007',
    scheme='SCT',
    meaning='right lateral',
)

PROJECTION_RIGHT_OBLIQUE = DicomCode(
    value='260424009',
    scheme='SCT',
    meaning='right lateral oblique',
)

PROJECTION_OBLIQUE = DicomCode(
    value='399182000',
    scheme='SCT',
    meaning='oblique',
)

PROJECTION_45DEG = DicomCode(
    value='260454004',
    scheme='SCT',
    meaning='45 degree projection',
)

PROJECTION_SUBMENTOVERTICAL = DicomCode(
    value='399255003',
    scheme='SCT',
    meaning='submentovertical',
)

PROJECTION_VERTEX = DicomCode(
    value='260461000',
    scheme='SCT',
    meaning='vertex',
)

PROJECTION_OCCLUSAL = DicomCode(
    value='260499007',
    scheme='SCT',
    meaning='Occlusal projection',
)

IMAGE_MIRRORED_UNCORRECTED = DicomCode(
    value='789135000',
    scheme='SCT',
    meaning='Mirrored image uncorrected',
)

IMAGE_MIRRORED_UNCORRECTED_FLIPPED_HORIZONTALLY = DicomCode(
    value='789134001',
    scheme='SCT',
    meaning='Mirrored image uncorrected flipped horizontally',
)

IMAGE_MIRRORED_UNCORRECTED_FLIPPED_HORIZONTALLY_VERTICALLY = DicomCode(
    value='789132002',
    scheme='SCT',
    meaning='Mirrored image uncorrected flipped horizontally and vertically',
)

IMAGE_MIRRORED_UNCORRECTED_FLIPPED_VERTICALLY = DicomCode(
    value='789133007',
    scheme='SCT',
    meaning='Mirrored image uncorrected flipped vertically',
)

CLOSEUP = DicomCode(
    value='789131009',
    scheme='SCT',
    meaning='Close up photographic view of teeth without magnification',
)

IMAGE_MIRRORED_CORRECTED = DicomCode(
    value='787610003',
    scheme='SCT',
    meaning='Mirrored photo image intraoral corrected',
)

IMAGE_MIRRORED_CORRECTED_FLIPPED_HORIZONTALLY = DicomCode(
    value='789310004',
    scheme='SCT',
    meaning='Mirrored photo image of teeth corrected flipped horizontally',
)

IMAGE_MIRRORED_CORRECTED_FLIPPED_VERTICALLY = DicomCode(
    value='789311000',
    scheme='SCT',
    meaning='Mirrored photo image of teeth corrected flipped vertically',
)

IMAGE_MIRRORED_CORRECTED_FLIPPED_HORIZONTALLY_VERTICALLY = DicomCode(
    value='789312007',
    scheme='SCT',
    meaning='Mirrored photo image of teeth corrected rotated 180 deg',
)

IMAGE_EXTRAORAL_45DEG = DicomCode(
    value='787612006',
    scheme='SCT',
    meaning='Photo image extraoral with 45 degree view',
)

IMAGE_EXTRAORAL_MPF = DicomCode(
    value='787611004',
    scheme='SCT',
    meaning='Photo image extraoral with mandible postured forward',
)

IMAGE_ANTERIOR_TEETH = DicomCode(
    value='789313002',
    scheme='SCT',
    meaning='Photo image of anterior teeth',
)

IMAGE_FACE_LIPS_RELAXED = DicomCode(
    value='789314008',
    scheme='SCT',
    meaning='Photo image of face with lips in relaxed position',
)

IMAGE_LIPS_CLOSED = DicomCode(
    value='787607005',
    scheme='SCT',
    meaning='Photo image with lips closed',
)

IMAGE_MOUTH_PARTIALLY_OPEN_TEETH_APART = DicomCode(
    value='789130005',
    scheme='SCT',
    meaning='Photo image with mouth partially opened and teeth apart',
)

MOUTH_OPEN = DicomCode(
    value='262016004',
    scheme='SCT',
    meaning='Open mouth',
)

MOUTH_PARTIALLY_OPEN = DicomCode(
    value='1332210001',
    scheme='SCT',
    meaning='Mouth in partially open position',
)

LIPS_RELAXED = DicomCode(
    value='1336028006',
    scheme='SCT',
    meaning='Upper and lower lips in relaxed position',
)

LIPS_CLOSED = DicomCode(
    value='1336029003',
    scheme='SCT',
    meaning='Upper and lower lips in closed position',
)

MPF = DicomCode(
    value='1336026005',
    scheme='SCT',
    meaning='Mandible postured forwards',
)

SMILE = DicomCode(
    value='225583004',
    scheme='SCT',
    meaning='Smiles',
)

SKIN_MARK = DicomCode(
    value='276470008',
    scheme='SCT',
    meaning='Skin mark',
)

TATTOO = DicomCode(
    value='341000119102',
    scheme='SCT',
    meaning='Tattoo of skin',
)

GINGIVAL_RECESSION = DicomCode(
    value='4356008',
    scheme='SCT',
    meaning='Gingival recession',
)

CANT = DicomCode(
    value='710793000',
    scheme='SCT',
    meaning='Cant of occlusal plane',
)

PIGMENTATION_MUCOSA_LEFT = DicomCode(
    value='1264188003',
    scheme='SCT',
    meaning='Tattoo of left buccal mucosa',
)

PIGMENTATION_MUCOSA_RIGHT = DicomCode(
    value='1264193000',
    scheme='SCT',
    meaning='Tattoo of right buccal mucosa',
)

PIGMENTATION_MUCOSA_SOFT_PALATE = DicomCode(
    value='1260043007',
    scheme='SCT',
    meaning='Tattoo of mucosa of soft palate',
)

PIGMENTATION_MUCOSA_LIP_LOWER = DicomCode(
    value='1260047008',
    scheme='SCT',
    meaning='Tattoo of labial mucosa of lower lip',
)

PIGMENTATION_MUCOSA_LIP_UPPER = DicomCode(
    value='1260049006',
    scheme='SCT',
    meaning='Tattoo of labial mucosa of upper lip',
)

PALSY = DicomCode(
    value='193093009',
    scheme='SCT',
    meaning="Bell's palsy",
)

TONGUE_THRUST = DicomCode(
    value='110343009',
    scheme='SCT',
    meaning='Tongue thrust',
)

CO = DicomCode(
    value='110320000',
    scheme='SCT',
    meaning='Centric occlusion',
)

CR = DicomCode(
    value='736783005',
    scheme='SCT',
    meaning='Centric relation',
)

PATIENT_REGISTRATION = DicomCode(
    value='184047000',
    scheme='SCT',
    meaning='Patient registration',
)

ORTHODONTIC_TREATMENT_STARTED = DicomCode(
    value='1332161000',
    scheme='SCT',
    meaning='Orthodontic Treatment started',
)

ORTHODONTIC_TREATMENT_STOPPED = DicomCode(
    value='1340210007',
    scheme='SCT',
    meaning='Orthodontic Treatment stopped',
)

DEVICE_PERIODONTAL_PROBE = DicomCode(
    value='462735007',
    scheme='SCT',
    meaning='Periodontal probe',
)

DEVICE_MIRROR = DicomCode(
    value='1332162007',
    scheme='SCT',
    meaning='Intraoral photography mirror',
)

DEVICE_TONGUE_DEPRESSOR = DicomCode(
    value='39802000',
    scheme='SCT',
    meaning='Tongue blade',
)

DEVICE_RULER = DicomCode(
    value='102304005',
    scheme='SCT',
    meaning='Measuring Ruler',
)

DEVICE_RETRACTOR = DicomCode(
    value='53535004',
    scheme='SCT',
    meaning='Retractor',
)

DEVICE_CONTRASTER = DicomCode(
    value='1332163002',
    scheme='SCT',
    meaning='Dental photography black contraster',
)

DEVICE_FIDUCIAL_MARKER = DicomCode(
    value='1332164008',
    scheme='SCT',
    meaning='Photographic image fiducial marker',
)

ORTHOGNATHIC_FUNCTIONAL_CONDITIONS = DicomCode(
    value='130325',
    scheme='DCM',
    meaning='Orthognathic Functional Condition',
)

TEMPORAL_EVENT_TYPE = DicomCode(
    value='128741',
    scheme='DCM',
    meaning='Longitudinal Temporal Event Type',
)

OFFSET_FROM_EVENT = DicomCode(
    value='128740',
    scheme='DCM',
    meaning='Longitudinal Temporal Offset from Event',
)


CODES: dict[str, DicomCode] = {
    'FindingByInspection': FINDING_BY_INSPECTION,
    'ObservableEntity': OBSERVABLE_ENTITY,
    'DentalOcclusion': DENTAL_OCCLUSION,
    'day': DAY,
    'LateralityBoth': LATERALITY_BOTH,
    'LateralityLeft': LATERALITY_LEFT,
    'LateralityRight': LATERALITY_RIGHT,
    'LateralityUnpaired': LATERALITY_UNPAIRED,
    'OrientationLeft': ORIENTATION_LEFT,
    'OrientationRight': ORIENTATION_RIGHT,
    'OrientationSupineHeadToFeet': ORIENTATION_SUPINE_HEAD_TO_FEET,
    'OrientationProneFeetToHead': ORIENTATION_PRONE_FEET_TO_HEAD,
    'OrientationFront': ORIENTATION_FRONT,
    'OrientationBack': ORIENTATION_BACK,
    'OrientationSupineFeetToHead': ORIENTATION_SUPINE_FEET_TO_HEAD,
    'OrientationProneHeadToFeet': ORIENTATION_PRONE_HEAD_TO_FEET,
    'right': RIGHT,
    'left': LEFT,
    'Mouth': MOUTH,
    'HeadNeck': HEAD_NECK,
    'dental_arch_mandibular': DENTAL_ARCH_MANDIBULAR,
    'dental_arch_maxillary': DENTAL_ARCH_MAXILLARY,
    'StructureOfBuccalSpace': STRUCTURE_OF_BUCCAL_SPACE,
    'frenum': FRENUM,
    'FaceStructure': FACE_STRUCTURE,
    'OralCavityStructure': ORAL_CAVITY_STRUCTURE,
    'projection_frontal': PROJECTION_FRONTAL,
    'projection_left': PROJECTION_LEFT,
    'projection_left_oblique': PROJECTION_LEFT_OBLIQUE,
    'projection_right': PROJECTION_RIGHT,
    'projection_right_oblique': PROJECTION_RIGHT_OBLIQUE,
    'projection_oblique': PROJECTION_OBLIQUE,
    'projection_45deg': PROJECTION_45DEG,
    'projection_submentovertical': PROJECTION_SUBMENTOVERTICAL,
    'projection_vertex': PROJECTION_VERTEX,
    'projection_occlusal': PROJECTION_OCCLUSAL,
    'image_mirrored_uncorrected': IMAGE_MIRRORED_UNCORRECTED,
    'image_mirrored_uncorrected_flipped_horizontally': IMAGE_MIRRORED_UNCORRECTED_FLIPPED_HORIZONTALLY,
    'image_mirrored_uncorrected_flipped_horizontally_vertically': IMAGE_MIRRORED_UNCORRECTED_FLIPPED_HORIZONTALLY_VERTICALLY,
    'image_mirrored_uncorrected_flipped_vertically': IMAGE_MIRRORED_UNCORRECTED_FLIPPED_VERTICALLY,
    'closeup': CLOSEUP,
    'image_mirrored_corrected': IMAGE_MIRRORED_CORRECTED,
    'image_mirrored_corrected_flipped_horizontally': IMAGE_MIRRORED_CORRECTED_FLIPPED_HORIZONTALLY,
    'image_mirrored_corrected_flipped_vertically': IMAGE_MIRRORED_CORRECTED_FLIPPED_VERTICALLY,
    'image_mirrored_corrected_flipped_horizontally_vertically': IMAGE_MIRRORED_CORRECTED_FLIPPED_HORIZONTALLY_VERTICALLY,
    'image_extraoral_45deg': IMAGE_EXTRAORAL_45DEG,
    'image_extraoral_mpf': IMAGE_EXTRAORAL_MPF,
    'image_anterior_teeth': IMAGE_ANTERIOR_TEETH,
    'image_face_lips_relaxed': IMAGE_FACE_LIPS_RELAXED,
    'image_lips_closed': IMAGE_LIPS_CLOSED,
    'image_mouth_partially_open_teeth_apart': IMAGE_MOUTH_PARTIALLY_OPEN_TEETH_APART,
    'mouth_open': MOUTH_OPEN,
    'mouth_partially_open': MOUTH_PARTIALLY_OPEN,
    'lips_relaxed': LIPS_RELAXED,
    'lips_closed': LIPS_CLOSED,
    'mpf': MPF,
    'smile': SMILE,
    'skin_mark': SKIN_MARK,
    'tattoo': TATTOO,
    'gingival_recession': GINGIVAL_RECESSION,
    'cant': CANT,
    'pigmentation_mucosa_left': PIGMENTATION_MUCOSA_LEFT,
    'pigmentation_mucosa_right': PIGMENTATION_MUCOSA_RIGHT,
    'pigmentation_mucosa_soft_palate': PIGMENTATION_MUCOSA_SOFT_PALATE,
    'pigmentation_mucosa_lip_lower': PIGMENTATION_MUCOSA_LIP_LOWER,
    'pigmentation_mucosa_lip_upper': PIGMENTATION_MUCOSA_LIP_UPPER,
    'palsy': PALSY,
    'tongue_thrust': TONGUE_THRUST,
    'co': CO,
    'cr': CR,
    'PatientRegistration': PATIENT_REGISTRATION,
    'OrthodonticTreatmentStarted': ORTHODONTIC_TREATMENT_STARTED,
    'OrthodonticTreatmentStopped': ORTHODONTIC_TREATMENT_STOPPED,
    'device_periodontal_probe': DEVICE_PERIODONTAL_PROBE,
    'device_mirror': DEVICE_MIRROR,
    'device_tongue_depressor': DEVICE_TONGUE_DEPRESSOR,
    'device_ruler': DEVICE_RULER,
    'device_retractor': DEVICE_RETRACTOR,
    'device_contraster': DEVICE_CONTRASTER,
    'device_fiducial_marker': DEVICE_FIDUCIAL_MARKER,
    'OrthognathicFunctionalConditions': ORTHOGNATHIC_FUNCTIONAL_CONDITIONS,
    'TemporalEventType': TEMPORAL_EVENT_TYPE,
    'OffsetFromEvent': OFFSET_FROM_EVENT,
}


IMAGE_TYPES: dict[str, AdaImageType] = {
    'IV01': AdaImageType(
        keyword='IV01',
        abbreviation='IO.RB.CO.NM',
        meaning='Intraoral, Right Buccal Segment, Centric Occlusion, No Mirror (Direct View)',
        code=DicomCode(value='IV01', scheme='99ADA1100', meaning='Intraoral photo,right buccal,centric occl.,no mirror'),
    ),
    'IV02': AdaImageType(
        keyword='IV02',
        abbreviation='IO.RB.CO.WM',
        meaning='Intraoral, Right Buccal Segment, Centric Occlusion, With Mirror',
        code=DicomCode(value='IV02', scheme='99ADA1100', meaning='Intraoral photo,right buccal,centric occl.,mirror'),
    ),
    'IV03': AdaImageType(
        keyword='IV03',
        abbreviation='IO.RB.CO.WM.BC',
        meaning='Intraoral, Right Buccal Segment, Centric Occlusion, With Mirror, But Corrected',
        code=DicomCode(value='IV03', scheme='99ADA1100', meaning='Intraoral photo,right buccal,centric occl.,mirror,corrected'),
    ),
    'IV04': AdaImageType(
        keyword='IV04',
        abbreviation='IO.RB.CR.NM',
        meaning='Intraoral, Right Buccal Segment, Centric Relation, No Mirror (Direct View)',
        code=DicomCode(value='IV04', scheme='99ADA1100', meaning='Intraoral photo,right buccal,centric relation,no mirror'),
    ),
    'IV05': AdaImageType(
        keyword='IV05',
        abbreviation='IO.RB.CR.WM',
        meaning='Intraoral, Right Buccal Segment, Centric Relation, With Mirror',
        code=DicomCode(value='IV05', scheme='99ADA1100', meaning='Intraoral photo,right buccal,centric relation,mirror'),
    ),
    'IV06': AdaImageType(
        keyword='IV06',
        abbreviation='IO.RB.CR.WM.BC',
        meaning='Intraoral, Right Buccal Segment, Centric Relation, With Mirror, But Corrected',
        code=DicomCode(value='IV06', scheme='99ADA1100', meaning='Intraoral photo,right buccal,centric relation,mirror,corrected'),
    ),
    'IV07': AdaImageType(
        keyword='IV07',
        abbreviation='IO.FV.CO.NM',
        meaning='Intraoral, Frontal View, Centric Occlusion, No Mirror (Direct View)',
        code=DicomCode(value='IV07', scheme='99ADA1100', meaning='Intraoral photo,frontal,centric occl.,no mirror'),
    ),
    'IV08': AdaImageType(
        keyword='IV08',
        abbreviation='IO.FV.CR.NM',
        meaning='Intraoral, Frontal View, Centric Relation, No Mirror (Direct View)',
        code=DicomCode(value='IV08', scheme='99ADA1100', meaning='Intraoral photo,frontal,centric relation,no mirror'),
    ),
    'IV09': AdaImageType(
        keyword='IV09',
        abbreviation='IO.FV.TA.NM',
        meaning='Intraoral, Frontal View, Teeth Apart, No Mirror (Direct View)',
        code=DicomCode(value='IV09', scheme='99ADA1100', meaning='Intraoral photo,frontal,teeth apart,no mirror'),
    ),
    'IV10': AdaImageType(
        keyword='IV10',
        abbreviation='IO.FV.MO.NM',
        meaning='Intraoral, Frontal View, Mouth Open, No Mirror (Direct View)',
        code=DicomCode(value='IV10', scheme='99ADA1100', meaning='Intraoral photo,frontal,mouth open,no mirror'),
    ),
    'IV11': AdaImageType(
        keyword='IV11',
        abbreviation='IO.FV.IV.CO.NM',
        meaning='Intraoral, Frontal View Inferior (showing depth of bite and overjet), Centric Occlusion, No Mirror (Direct View)',
        code=DicomCode(value='IV11', scheme='99ADA1100', meaning='Intraoral photo,front view inferior,centric occl.,no mirror'),
    ),
    'IV12': AdaImageType(
        keyword='IV12',
        abbreviation='IO.FV.IV.CR.NM',
        meaning='Intraoral, Frontal View Inferior (showing depth of bite and overjet), Centric Relation, No Mirror (Direct View)',
        code=DicomCode(value='IV12', scheme='99ADA1100', meaning='Intraoral photo,front view inferior,centric relation,no mirror'),
    ),
    'IV13': AdaImageType(
        keyword='IV13',
        abbreviation='IO.FV.TT.NM',
        meaning='Intraoral, Frontal View, showing Tongue Thrust, No Mirror (Direct View)',
        code=DicomCode(value='IV13', scheme='99ADA1100', meaning='Intraoral photo,frontal,tongue thrust,no mirror'),
    ),
    'IV14': AdaImageType(
        keyword='IV14',
        abbreviation='IO.RL.CO.OJ.NM',
        meaning='Intraoral, Right Lateral View, Centric Occlusion, showing Overjet, No Mirror (Direct View showing overjet from the side)',
        code=DicomCode(value='IV14', scheme='99ADA1100', meaning='Intraoral photo,right lateral,centric occl.,overjet,no mirror'),
    ),
    'IV15': AdaImageType(
        keyword='IV15',
        abbreviation='IO.RL.CR.OJ.NM',
        meaning='Intraoral, Right Lateral View, Centric Relation, showing Overjet, No Mirror (Direct View showing overjet from the side)',
        code=DicomCode(value='IV15', scheme='99ADA1100', meaning='Intraoral photo,right lateral,centric relation,overjet,no mirror'),
    ),
    'IV16': AdaImageType(
        keyword='IV16',
        abbreviation='IO.LL.CO.OJ.NM',
        meaning='Intraoral, Left Lateral View, Centric Occlusion, showing Overjet, No Mirror (Direct View showing overjet from the side)',
        code=DicomCode(value='IV16', scheme='99ADA1100', meaning='Intraoral photo,left lateral,centric occl.,overjet,no mirror'),
    ),
    'IV17': AdaImageType(
        keyword='IV17',
        abbreviation='IO.LL.CR.OJ.NM',
        meaning='Intraoral, Left Lateral View, Centric Relation, showing Overjet, No Mirror (Direct View showing overjet from the side)',
        code=DicomCode(value='IV17', scheme='99ADA1100', meaning='Intraoral photo,left lateral,centric relation,overjet,no mirror'),
    ),
    'IV18': AdaImageType(
        keyword='IV18',
        abbreviation='IO.LB.CO.NM',
        meaning='Intraoral, Left Buccal Segment, Centric Occlusion, No Mirror (Direct View)',
        code=DicomCode(value='IV18', scheme='99ADA1100', meaning='Intraoral photo,left buccal,centric occl.,no mirror'),
    ),
    'IV19': AdaImageType(
        keyword='IV19',
        abbreviation='IO.LB.CO.WM',
        meaning='Intraoral, Left Buccal Segment, Centric Occlusion, With Mirror',
        code=DicomCode(value='IV19', scheme='99ADA1100', meaning='Intraoral photo,left buccal,centric occl.,mirror'),
    ),
    'IV20': AdaImageType(
        keyword='IV20',
        abbreviation='IO.LB.CO.WM.BC',
        meaning='Intraoral, Left Buccal Segment, Centric Occlusion, With Mirror, But Corrected',
        code=DicomCode(value='IV20', scheme='99ADA1100', meaning='Intraoral photo,left buccal,centric occl.,mirror,corrected'),
    ),
    'IV21': AdaImageType(
        keyword='IV21',
        abbreviation='IO.LB.CR.NM',
        meaning='Intraoral, Left Buccal Segment, Centric Relation, No Mirror (Direct View)',
        code=DicomCode(value='IV21', scheme='99ADA1100', meaning='Intraoral photo,left buccal,centric relation,no mirror'),
    ),
    'IV22': AdaImageType(
        keyword='IV22',
        abbreviation='IO.LB.CR.WM',
        meaning='Intraoral, Left Buccal Segment, Centric Relation, With Mirror',
        code=DicomCode(value='IV22', scheme='99ADA1100', meaning='Intraoral photo,left buccal,centric relation,mirror'),
    ),
    'IV23': AdaImageType(
        keyword='IV23',
        abbreviation='IO.LB.CR.WM.BC',
        meaning='Intraoral, Left Buccal Segment, Centric Relation, With Mirror, But Corrected',
        code=DicomCode(value='IV23', scheme='99ADA1100', meaning='Intraoral photo,left buccal,centric relation,mirror,corrected'),
    ),
    'IV24': AdaImageType(
        keyword='IV24',
        abbreviation='IO.MX.MO.OV.WM',
        meaning='Intraoral, Maxillary, Mouth Open, Occlusal View, With Mirror',
        code=DicomCode(value='IV24', scheme='99ADA1100', meaning='Intraoral photo,maxillary,mouth open,occlusal,mirror'),
    ),
    'IV25': AdaImageType(
        keyword='IV25',
        abbreviation='IO.MX.MO.OV.WM.BC',
        meaning='Intraoral, Maxillary, Mouth Open, Occlusal View, With Mirror, But Corrected',
        code=DicomCode(value='IV25', scheme='99ADA1100', meaning='Intraoral photo,maxillary,mouth open,occlusal,mirror,corrected'),
    ),
    'IV26': AdaImageType(
        keyword='IV26',
        abbreviation='IO.MD.MO.OV.WM',
        meaning='Intraoral, Mandibular, Mouth Open, Occlusal View, With Mirror',
        code=DicomCode(value='IV26', scheme='99ADA1100', meaning='Intraoral photo,mandibular,mouth open,occlusal,mirror'),
    ),
    'IV27': AdaImageType(
        keyword='IV27',
        abbreviation='IO.MD.MO.OV.WM.BC',
        meaning='Intraoral, Mandibular, Mouth Open, Occlusal View, With Mirror, But Corrected',
        code=DicomCode(value='IV27', scheme='99ADA1100', meaning='Intraoral photo,mandibular,mouth open,occlusal,mirror,corrected'),
    ),
    'IV28': AdaImageType(
        keyword='IV28',
        abbreviation='IO.GR.[tooth number]',
        meaning='Intraoral, showing Gingival Recession. May include ISO tooth numbers of the affected teeth.',
        code=DicomCode(value='IV28', scheme='99ADA1100', meaning='Intraoral photo,gingival recession'),
    ),
    'IV29': AdaImageType(
        keyword='IV29',
        abbreviation='IO.FR.[tooth number]',
        meaning="Intraoral, showing Frenum. May include ISO tooth numbers designating frenum's location.",
        code=DicomCode(value='IV29', scheme='99ADA1100', meaning='Intraoral photo,frenum'),
    ),
    'IV30': AdaImageType(
        keyword='IV30',
        abbreviation='IO.[modifier].PA',
        meaning='Intraoral, any view using a photo accessory device such as a contraster to provide a solid background or black mirror ([modifier] is any set of IO modifier as specified above)',
        code=DicomCode(value='IV30', scheme='99ADA1100', meaning='Intraoral photo,photo accessory'),
    ),
    'EV01': AdaImageType(
        keyword='EV01',
        abbreviation='EO.RP.LR.CO',
        meaning="Extraoral, Right Profile (Subject is facing observer's right), Lips Relaxed, Centric Occlusion",
        code=DicomCode(value='EV01', scheme='99ADA1100', meaning='Extraoral photo,right profile,lips relaxed,centric occlusion'),
    ),
    'EV02': AdaImageType(
        keyword='EV02',
        abbreviation='EO.RP.LR.CR',
        meaning='Extraoral, Right Profile (Subject is facing observe right), Lips Relaxed, Centric Relation',
        code=DicomCode(value='EV02', scheme='99ADA1100', meaning='Extraoral photo,right profile,lips relaxed,centric relation'),
    ),
    'EV03': AdaImageType(
        keyword='EV03',
        abbreviation='EO.RP.LC.CO',
        meaning="Extraoral, Right Profile (Subject is facing observer's right), Lips Closed, Centric Occlusion",
        code=DicomCode(value='EV03', scheme='99ADA1100', meaning='Extraoral photo,right profile,lips closed,centric occlusion'),
    ),
    'EV04': AdaImageType(
        keyword='EV04',
        abbreviation='EO.RP.LC.CR',
        meaning="Extraoral, Right Profile (Patient is facing observer's right), Lips Closed, Centric Relation",
        code=DicomCode(value='EV04', scheme='99ADA1100', meaning='Extraoral photo,right profile,lips closed,centric relation'),
    ),
    'EV05': AdaImageType(
        keyword='EV05',
        abbreviation='EO.RP.FS.CO',
        meaning="Extraoral, Right profile (Patient is facing observer's right), Full Smile, Centric Occlusion",
        code=DicomCode(value='EV05', scheme='99ADA1100', meaning='Extraoral photo,right profile,full smile,centric occlusion'),
    ),
    'EV06': AdaImageType(
        keyword='EV06',
        abbreviation='EO.RP.FS.CR',
        meaning="Extraoral, Right Profile (Patient is facing observer's right), Full Smile, Centric Relation",
        code=DicomCode(value='EV06', scheme='99ADA1100', meaning='Extraoral photo,right profile,full smile,centric relation'),
    ),
    'EV07': AdaImageType(
        keyword='EV07',
        abbreviation='EO.RP.MD.PF',
        meaning="Extraoral, Right Profile (Patient is facing observer's right), Mandible Postured Forward",
        code=DicomCode(value='EV07', scheme='99ADA1100', meaning='Extraoral photo,right profile,mandible postured forward'),
    ),
    'EV08': AdaImageType(
        keyword='EV08',
        abbreviation='EO.RP.LR.CO.45',
        meaning="Extraoral, 45° Right Profile (Patient turns toward observer's right), Lips Relaxed, Centric Occlusion",
        code=DicomCode(value='EV08', scheme='99ADA1100', meaning='Extraoral photo,right profile 45,lips relaxed,centric occlusion'),
    ),
    'EV09': AdaImageType(
        keyword='EV09',
        abbreviation='EO.RP.LR.CR.45',
        meaning="Extraoral, 45° Right Profile (Patient turns toward observer's right), Lips Relaxed, Centric Relation",
        code=DicomCode(value='EV09', scheme='99ADA1100', meaning='Extraoral photo,right profile 45,lips relaxed,centric relation'),
    ),
    'EV10': AdaImageType(
        keyword='EV10',
        abbreviation='EO.RP.LC.CO.45',
        meaning="Extraoral, 45° Right Profile (Patient turns toward observer's right), Lips Closed, Centric Occlusion",
        code=DicomCode(value='EV10', scheme='99ADA1100', meaning='Extraoral photo,right profile 45,lips closed,centric occlusion'),
    ),
    'EV11': AdaImageType(
        keyword='EV11',
        abbreviation='EO.RP.LC.CR.45',
        meaning="Extraoral, 45° Right Profile (Patient turns toward observer's right), Lips Closed, Centric Relation",
        code=DicomCode(value='EV11', scheme='99ADA1100', meaning='Extraoral photo,right profile 45,lips closed,centric relation'),
    ),
    'EV12': AdaImageType(
        keyword='EV12',
        abbreviation='EO.RP.FS.CO.45',
        meaning="Extraoral, 45° Right Profile (Patient turns toward observer's right), Full Smile, Centric Occlusion",
        code=DicomCode(value='EV12', scheme='99ADA1100', meaning='Extraoral photo,right profile 45,full smile,centric occlusion'),
    ),
    'EV13': AdaImageType(
        keyword='EV13',
        abbreviation='EO.RP.FS.CR.45',
        meaning="Extraoral, 45° Right Profile (Patient turns toward observer's right), Full Smile, Centric Relation",
        code=DicomCode(value='EV13', scheme='99ADA1100', meaning='Extraoral photo,right profile 45,full smile,centric relation'),
    ),
    'EV14': AdaImageType(
        keyword='EV14',
        abbreviation='EO.RP.MD.PF.45',
        meaning="Extraoral, 45° Right Profile (Patient turns toward observer's right), Mandible Postured Forward",
        code=DicomCode(value='EV14', scheme='99ADA1100', meaning='Extraoral photo,right profile 45,mandible postured forward'),
    ),
    'EV15': AdaImageType(
        keyword='EV15',
        abbreviation='EO.FF.LR.CO',
        meaning='Extraoral, Full Face, Lips Relaxed, Centric Occlusion',
        code=DicomCode(value='EV15', scheme='99ADA1100', meaning='Extraoral photo,full face,lips relaxed,centric occlusion'),
    ),
    'EV16': AdaImageType(
        keyword='EV16',
        abbreviation='EO.FF.LR.CR',
        meaning='Extraoral, Full Face, Lips Relaxed, Centric Relation',
        code=DicomCode(value='EV16', scheme='99ADA1100', meaning='Extraoral photo,full face,lips relaxed,centric relation'),
    ),
    'EV17': AdaImageType(
        keyword='EV17',
        abbreviation='EO.FF.LC.CO',
        meaning='Extraoral, Full Face, Lips Closed, Centric Occlusion',
        code=DicomCode(value='EV17', scheme='99ADA1100', meaning='Extraoral photo,full face,lips closed,centric occlusion'),
    ),
    'EV18': AdaImageType(
        keyword='EV18',
        abbreviation='EO.FF.LC.CR',
        meaning='Extraoral, Full Face, Lips Closed, Centric Relation',
        code=DicomCode(value='EV18', scheme='99ADA1100', meaning='Extraoral photo,full face,lips closed,centric relation'),
    ),
    'EV19': AdaImageType(
        keyword='EV19',
        abbreviation='EO.FF.FS.CO',
        meaning='Extraoral, Full Face, Full Smile, Centric Occlusion',
        code=DicomCode(value='EV19', scheme='99ADA1100', meaning='Extraoral photo,full face,full smile,centric occlusion'),
    ),
    'EV20': AdaImageType(
        keyword='EV20',
        abbreviation='EO.FF.FS.CR',
        meaning='Extraoral, Full Face, Full Smile, Centric Relation',
        code=DicomCode(value='EV20', scheme='99ADA1100', meaning='Extraoral photo,full face,full smile,centric relation'),
    ),
    'EV21': AdaImageType(
        keyword='EV21',
        abbreviation='EO.FF.MD.PF',
        meaning='Extraoral, Full Face, Mandible Postured Forward',
        code=DicomCode(value='EV21', scheme='99ADA1100', meaning='Extraoral photo,full face,mandible postured forward'),
    ),
    'EV22': AdaImageType(
        keyword='EV22',
        abbreviation='EO.LP.LR.CO',
        meaning="Extraoral, Left Profile (Patient is facing observer's left), Lips Relaxed, Centric Occlusion",
        code=DicomCode(value='EV22', scheme='99ADA1100', meaning='Extraoral photo,left profile,lips relaxed,centric occlusion'),
    ),
    'EV23': AdaImageType(
        keyword='EV23',
        abbreviation='EO.LP.LR.CR',
        meaning="Extraoral, Left Profile (Patient is facing observer's left), Lips Relaxed, Centric Relation",
        code=DicomCode(value='EV23', scheme='99ADA1100', meaning='Extraoral photo,left profile,lips relaxed,centric relation'),
    ),
    'EV24': AdaImageType(
        keyword='EV24',
        abbreviation='EO.LP.LC.CO',
        meaning="Extraoral, Left Profile (Patient is facing observer's left), Lips Closed, Centric Occlusion",
        code=DicomCode(value='EV24', scheme='99ADA1100', meaning='Extraoral photo,left profile,lips closed,centric occlusion'),
    ),
    'EV25': AdaImageType(
        keyword='EV25',
        abbreviation='EO.LP.LC.CR',
        meaning="Extraoral, Left Profile (Patient is facing observer's left), Lips Closed, Centric Relation",
        code=DicomCode(value='EV25', scheme='99ADA1100', meaning='Extraoral photo,left profile,lips closed,centric relation'),
    ),
    'EV26': AdaImageType(
        keyword='EV26',
        abbreviation='EO.LP.FS.CO',
        meaning="Extraoral, Left profile (Patient is facing observer's left), Full Smile, Centric Occlusion",
        code=DicomCode(value='EV26', scheme='99ADA1100', meaning='Extraoral photo,left profile,full smile,centric occlusion'),
    ),
    'EV27': AdaImageType(
        keyword='EV27',
        abbreviation='EO.LP.FS.CR',
        meaning="Extraoral, Left Profile (Patient is facing observer's left), Full Smile, Centric Relation",
        code=DicomCode(value='EV27', scheme='99ADA1100', meaning='Extraoral photo,left profile,full smile,centric relation'),
    ),
    'EV28': AdaImageType(
        keyword='EV28',
        abbreviation='EO.LP.MD.PF',
        meaning="Extraoral, Left Profile (Patient is facing observer's left), Mandible Postured Forward",
        code=DicomCode(value='EV28', scheme='99ADA1100', meaning='Extraoral photo,left profile,mandible postured forward'),
    ),
    'EV29': AdaImageType(
        keyword='EV29',
        abbreviation='EO.LP.LR.CO.45',
        meaning="Extraoral, 45° Left Profile (Patient turns toward observer's left), Lips Relaxed, Centric Occlusion",
        code=DicomCode(value='EV29', scheme='99ADA1100', meaning='Extraoral photo,left profile 45,lips relaxed,centric occlusion'),
    ),
    'EV30': AdaImageType(
        keyword='EV30',
        abbreviation='EO.LP.LR.CR.45',
        meaning="Extraoral, 45° Left Profile (Patient turns toward observer's left), Lips Relaxed, Centric Relation",
        code=DicomCode(value='EV30', scheme='99ADA1100', meaning='Extraoral photo,left profile 45,lips relaxed,centric relation'),
    ),
    'EV31': AdaImageType(
        keyword='EV31',
        abbreviation='EO.LP.LC.CO.45',
        meaning="Extraoral, 45° Left Profile (Patient turns toward observer's left), Lips Closed, Centric Occlusion",
        code=DicomCode(value='EV31', scheme='99ADA1100', meaning='Extraoral photo,left profile 45,lips closed,centric occlusion'),
    ),
    'EV32': AdaImageType(
        keyword='EV32',
        abbreviation='EO.LP.LC.CR.45',
        meaning="Extraoral, 45° Left Profile (Patient turns toward observer's left), Lips Closed, Centric Relation",
        code=DicomCode(value='EV32', scheme='99ADA1100', meaning='Extraoral photo,left profile 45,lips closed,centric relation'),
    ),
    'EV33': AdaImageType(
        keyword='EV33',
        abbreviation='EO.LP.FS.CO.45',
        meaning="Extraoral, 45° Left Profile (Patient turns toward observer's left), Full Smile, Centric Occlusion",
        code=DicomCode(value='EV33', scheme='99ADA1100', meaning='Extraoral photo,left profile 45,full smile,centric occlusion'),
    ),
    'EV34': AdaImageType(
        keyword='EV34',
        abbreviation='EO.LP.FS.CR.45',
        meaning="Extraoral, 45° Left Profile (Patient turns toward observer's left, Full Smile, Centric Relation",
        code=DicomCode(value='EV34', scheme='99ADA1100', meaning='Extraoral photo,left profile 45,full smile,centric relation'),
    ),
    'EV35': AdaImageType(
        keyword='EV35',
        abbreviation='EO.LP.MD.PF.45',
        meaning="Extraoral, 45° Left Profile (Patient turns toward observer's left, Mandible Postured Forward",
        code=DicomCode(value='EV35', scheme='99ADA1100', meaning='Extraoral photo,left profile 45,mandible postured forward'),
    ),
    'EV36': AdaImageType(
        keyword='EV36',
        abbreviation='EO.OF.IV',
        meaning='Extraoral, Other Face (head tipped back), Inferior View (showing lower border of mandible, nares, infraorbital rim contours, forehead contours)',
        code=DicomCode(value='EV36', scheme='99ADA1100', meaning='Extraoral photo,other face,inferior view'),
    ),
    'EV37': AdaImageType(
        keyword='EV37',
        abbreviation='EO.OF.SV',
        meaning='Extraoral, Other Face (viewed from above), Superior View (showing forehead, infraorbital rim contour, dorsum of nose, upper lip, chin)',
        code=DicomCode(value='EV37', scheme='99ADA1100', meaning='Extraoral photo,other face,superior view'),
    ),
    'EV38': AdaImageType(
        keyword='EV38',
        abbreviation='EO.OF.CS',
        meaning='Extraoral, Other Face, Close-Up Smile (with lips)',
        code=DicomCode(value='EV38', scheme='99ADA1100', meaning='Extraoral photo,other face,close-up smile'),
    ),
    'EV39': AdaImageType(
        keyword='EV39',
        abbreviation='EO.OF.OC',
        meaning='Extraoral, Other Face, Occlusal Cant (e.g., tongue depressor between the teeth)',
        code=DicomCode(value='EV39', scheme='99ADA1100', meaning='Extraoral photo,other face,occlusal cant'),
    ),
    'EV40': AdaImageType(
        keyword='EV40',
        abbreviation='EO.OF.FI',
        meaning='Extraoral, Other Face, Forensic Interest (tattoos, jewelry, scars)',
        code=DicomCode(value='EV40', scheme='99ADA1100', meaning='Extraoral photo,other face,forensic interest'),
    ),
    'EV41': AdaImageType(
        keyword='EV41',
        abbreviation='EO.OF.AN',
        meaning='Extraoral, Other Face, Anomalies (ears, skin tags, etc.)',
        code=DicomCode(value='EV41', scheme='99ADA1100', meaning='Extraoral photo,other face,anomalies'),
    ),
    'EV42': AdaImageType(
        keyword='EV42',
        abbreviation='EO.FF.MO',
        meaning='Extraoral, Full Face, Mouth Open',
        code=DicomCode(value='EV42', scheme='99ADA1100', meaning='Extraoral photo,full face,mouth open'),
    ),
    'EV43': AdaImageType(
        keyword='EV43',
        abbreviation='EO.FF.NW',
        meaning='Extraoral, Full Face, demonstrating Nerve Weakness',
        code=DicomCode(value='EV43', scheme='99ADA1100', meaning='Extraoral photo,full face,demonstrating nerve weakness'),
    ),
}


VIEWS: dict[str, OrthoView] = {
    'IV01': OrthoView(
        keyword='IV01',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Right Buccal Segment, Centric Occlusion, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV02': OrthoView(
        keyword='IV02',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Right Buccal Segment, Centric Occlusion, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV03': OrthoView(
        keyword='IV03',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Right Buccal Segment, Centric Occlusion, With Mirror, But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV04': OrthoView(
        keyword='IV04',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Right Buccal Segment, Centric Relation, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV05': OrthoView(
        keyword='IV05',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Right Buccal Segment, Centric Relation, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV06': OrthoView(
        keyword='IV06',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Right Buccal Segment, Centric Relation, With Mirror, But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV07': OrthoView(
        keyword='IV07',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Frontal View, Centric Occlusion, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV08': OrthoView(
        keyword='IV08',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Frontal View, Centric Relation, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV09': OrthoView(
        keyword='IV09',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(IMAGE_MOUTH_PARTIALLY_OPEN_TEETH_APART,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral, Frontal View, Teeth Apart, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV10': OrthoView(
        keyword='IV10',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral, Frontal View, Mouth Open, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV11': OrthoView(
        keyword='IV11',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Frontal View Inferior (showing depth of bite and overjet), Centric Occlusion, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV12': OrthoView(
        keyword='IV12',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Frontal View Inferior (showing depth of bite and overjet), Centric Relation, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV13': OrthoView(
        keyword='IV13',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(TONGUE_THRUST,),
        dental_occlusion=CO,
        description='Intraoral, Frontal View, showing Tongue Thrust, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV14': OrthoView(
        keyword='IV14',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_RULER,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Right Lateral View, Centric Occlusion, showing Overjet, No Mirror (Direct View showing overjet from the side)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV15': OrthoView(
        keyword='IV15',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Right Lateral View, Centric Relation, showing Overjet, No Mirror (Direct View showing overjet from the side)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV16': OrthoView(
        keyword='IV16',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Left Lateral View, Centric Occlusion, showing Overjet, No Mirror (Direct View showing overjet from the side)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV17': OrthoView(
        keyword='IV17',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Left Lateral View, Centric Relation, showing Overjet, No Mirror (Direct View showing overjet from the side)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV18': OrthoView(
        keyword='IV18',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Left Buccal Segment, Centric Occlusion, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV19': OrthoView(
        keyword='IV19',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_LEFT,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral, Left Buccal Segment, Centric Occlusion, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV20': OrthoView(
        keyword='IV20',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_LEFT,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Left Buccal Segment, Centric Occlusion, With Mirror, But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV21': OrthoView(
        keyword='IV21',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Left Buccal Segment, Centric Relation, No Mirror (Direct View)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV22': OrthoView(
        keyword='IV22',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_LEFT,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Left Buccal Segment, Centric Relation, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV23': OrthoView(
        keyword='IV23',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_LEFT,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral, Left Buccal Segment, Centric Relation, With Mirror, But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV24': OrthoView(
        keyword='IV24',
        patient_orientation=('R', 'A'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=DENTAL_ARCH_MAXILLARY,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_OCCLUSAL,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral, Maxillary, Mouth Open, Occlusal View, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV25': OrthoView(
        keyword='IV25',
        patient_orientation=('L', 'P'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=DENTAL_ARCH_MAXILLARY,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_OCCLUSAL,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral, Maxillary, Mouth Open, Occlusal View, With Mirror, But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV26': OrthoView(
        keyword='IV26',
        patient_orientation=('L', 'P'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=DENTAL_ARCH_MANDIBULAR,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_OCCLUSAL,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral, Mandibular, Mouth Open, Occlusal View, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV27': OrthoView(
        keyword='IV27',
        patient_orientation=('L', 'A'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=DENTAL_ARCH_MANDIBULAR,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_OCCLUSAL,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral, Mandibular, Mouth Open, Occlusal View, With Mirror, But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV28': OrthoView(
        keyword='IV28',
        patient_orientation=None,
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=None,
        view_modifiers=(CLOSEUP,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(GINGIVAL_RECESSION,),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral, showing Gingival Recession. May include ISO tooth numbers of the affected teeth.',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV29': OrthoView(
        keyword='IV29',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FRENUM,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=None,
        view_modifiers=(CLOSEUP,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="Intraoral, showing Frenum. May include ISO tooth numbers designating frenum's location.",
        series_description='Orthodontic Intraoral Series',
    ),

    'IV30': OrthoView(
        keyword='IV30',
        patient_orientation=None,
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_PERIODONTAL_PROBE,),
        view_code=None,
        view_modifiers=(),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral, any view using a photo accessory device such as a contraster to provide a solid background or black mirror ([modifier] is any set of IO modifier as specified above)',
        series_description='Orthodontic Intraoral Series',
    ),

    'EV01': OrthoView(
        keyword='EV01',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, Right Profile (Subject is facing observer's right), Lips Relaxed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV02': OrthoView(
        keyword='EV02',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Extraoral, Right Profile (Subject is facing observe right), Lips Relaxed, Centric Relation',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV03': OrthoView(
        keyword='EV03',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, Right Profile (Subject is facing observer's right), Lips Closed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV04': OrthoView(
        keyword='EV04',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, Right Profile (Patient is facing observer's right), Lips Closed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV05': OrthoView(
        keyword='EV05',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, Right profile (Patient is facing observer's right), Full Smile, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV06': OrthoView(
        keyword='EV06',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, Right Profile (Patient is facing observer's right), Full Smile, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV07': OrthoView(
        keyword='EV07',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="Extraoral, Right Profile (Patient is facing observer's right), Mandible Postured Forward",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV08': OrthoView(
        keyword='EV08',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, 45° Right Profile (Patient turns toward observer's right), Lips Relaxed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV09': OrthoView(
        keyword='EV09',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, 45° Right Profile (Patient turns toward observer's right), Lips Relaxed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV10': OrthoView(
        keyword='EV10',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, 45° Right Profile (Patient turns toward observer's right), Lips Closed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV11': OrthoView(
        keyword='EV11',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, 45° Right Profile (Patient turns toward observer's right), Lips Closed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV12': OrthoView(
        keyword='EV12',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, 45° Right Profile (Patient turns toward observer's right), Full Smile, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV13': OrthoView(
        keyword='EV13',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, 45° Right Profile (Patient turns toward observer's right), Full Smile, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV14': OrthoView(
        keyword='EV14',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="Extraoral, 45° Right Profile (Patient turns toward observer's right), Mandible Postured Forward",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV15': OrthoView(
        keyword='EV15',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Extraoral, Full Face, Lips Relaxed, Centric Occlusion',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV16': OrthoView(
        keyword='EV16',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Extraoral, Full Face, Lips Relaxed, Centric Relation',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV17': OrthoView(
        keyword='EV17',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Extraoral, Full Face, Lips Closed, Centric Occlusion',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV18': OrthoView(
        keyword='EV18',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Extraoral, Full Face, Lips Closed, Centric Relation',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV19': OrthoView(
        keyword='EV19',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Extraoral, Full Face, Full Smile, Centric Occlusion',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV20': OrthoView(
        keyword='EV20',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Extraoral, Full Face, Full Smile, Centric Relation',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV21': OrthoView(
        keyword='EV21',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Extraoral, Full Face, Mandible Postured Forward',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV22': OrthoView(
        keyword='EV22',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, Left Profile (Patient is facing observer's left), Lips Relaxed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV23': OrthoView(
        keyword='EV23',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, Left Profile (Patient is facing observer's left), Lips Relaxed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV24': OrthoView(
        keyword='EV24',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, Left Profile (Patient is facing observer's left), Lips Closed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV25': OrthoView(
        keyword='EV25',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, Left Profile (Patient is facing observer's left), Lips Closed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV26': OrthoView(
        keyword='EV26',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, Left profile (Patient is facing observer's left), Full Smile, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV27': OrthoView(
        keyword='EV27',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, Left Profile (Patient is facing observer's left), Full Smile, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV28': OrthoView(
        keyword='EV28',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="Extraoral, Left Profile (Patient is facing observer's left), Mandible Postured Forward",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV29': OrthoView(
        keyword='EV29',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, 45° Left Profile (Patient turns toward observer's left), Lips Relaxed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV30': OrthoView(
        keyword='EV30',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, 45° Left Profile (Patient turns toward observer's left), Lips Relaxed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV31': OrthoView(
        keyword='EV31',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, 45° Left Profile (Patient turns toward observer's left), Lips Closed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV32': OrthoView(
        keyword='EV32',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, 45° Left Profile (Patient turns toward observer's left), Lips Closed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV33': OrthoView(
        keyword='EV33',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Extraoral, 45° Left Profile (Patient turns toward observer's left), Full Smile, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV34': OrthoView(
        keyword='EV34',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Extraoral, 45° Left Profile (Patient turns toward observer's left, Full Smile, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV35': OrthoView(
        keyword='EV35',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE, MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="Extraoral, 45° Left Profile (Patient turns toward observer's left, Mandible Postured Forward",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV36': OrthoView(
        keyword='EV36',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_SUBMENTOVERTICAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Extraoral, Other Face (head tipped back), Inferior View (showing lower border of mandible, nares, infraorbital rim contours, forehead contours)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV37': OrthoView(
        keyword='EV37',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_VERTEX,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Extraoral, Other Face (viewed from above), Superior View (showing forehead, infraorbital rim contour, dorsum of nose, upper lip, chin)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV38': OrthoView(
        keyword='EV38',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(CLOSEUP,),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Extraoral, Other Face, Close-Up Smile (with lips)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV39': OrthoView(
        keyword='EV39',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_TONGUE_DEPRESSOR,),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(CANT,),
        observable_entities=(),
        dental_occlusion=None,
        description='Extraoral, Other Face, Occlusal Cant (e.g., tongue depressor between the teeth)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV40': OrthoView(
        keyword='EV40',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=None,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Extraoral, Other Face, Forensic Interest (tattoos, jewelry, scars)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV41': OrthoView(
        keyword='EV41',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Extraoral, Other Face, Anomalies (ears, skin tags, etc.)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV42': OrthoView(
        keyword='EV42',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Extraoral, Full Face, Mouth Open',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV43': OrthoView(
        keyword='EV43',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(PALSY,),
        dental_occlusion=None,
        description='Extraoral, Full Face, demonstrating Nerve Weakness',
        series_description='Orthodontic Extraoral Series',
    ),

}
