"""
Auto-generated by tools/generate_codes.py — DO NOT EDIT MANUALLY.
Regenerate with:  python tools/generate_codes.py
"""

from __future__ import annotations
from dicom4ortho.m_dent_oip import DicomCode, OrthoView


# -----------------------------------------------------------------------
# DicomCode constants (one per row in codes.csv)
# -----------------------------------------------------------------------

FUNCTIONAL_CONDITION_PRESENT_DURING_ACQUISITION = DicomCode(
    value='130324',
    scheme='DCM',
    meaning='Functional condition present during acquisition',
)

ORTHOGNATHIC_FUNCTIONAL_CONDITIONS = DicomCode(
    value='130325',
    scheme='DCM',
    meaning='Orthognathic Functional Conditions',
)

MOUTH_OPEN = DicomCode(
    value='262016004',
    scheme='SCT',
    meaning='Open mouth (finding)',
)

MOUTH_PARTIALLY_OPEN = DicomCode(
    value='1332210001',
    scheme='SCT',
    meaning='Mouth in partially open position',
)

LIPS_RELAXED = DicomCode(
    value='1336028006',
    scheme='SCT',
    meaning='Upper and lower lips in relaxed position',
)

LIPS_CLOSED = DicomCode(
    value='1336029003',
    scheme='SCT',
    meaning='Upper and lower lips in closed position',
)

MPF = DicomCode(
    value='1336026005',
    scheme='SCT',
    meaning='Mandible postured forward (record artifact)',
)

SMILE = DicomCode(
    value='225583004',
    scheme='SCT',
    meaning='Smiles (finding)',
)

FINDING_BY_INSPECTION = DicomCode(
    value='118243007',
    scheme='SCT',
    meaning='Finding By Inspection',
)

SKIN_MARK = DicomCode(
    value='276470008',
    scheme='SCT',
    meaning='Skin mark (disorder)',
)

SLAP_MARK = DicomCode(
    value='281689009',
    scheme='SCT',
    meaning='Slap mark (disorder)',
)

BIRTHMARK = DicomCode(
    value='51089004',
    scheme='SCT',
    meaning='Birthmark (disorder)',
)

TATTOO = DicomCode(
    value='341000119102',
    scheme='SCT',
    meaning='Tattoo of skin (finding)',
)

GINGIVAL_RECESSION = DicomCode(
    value='4356008',
    scheme='SCT',
    meaning='Gingival recession (disorder)',
)

CANT = DicomCode(
    value='710793000',
    scheme='SCT',
    meaning='Cant of occlusal plane (observable entity)',
)

PIGMENTATION_MUCOSA_LEFT = DicomCode(
    value='1264188003',
    scheme='SCT',
    meaning='Local exogenous pigmentation of left buccal mucosa',
)

PIGMENTATION_MUCOSA_RIGHT = DicomCode(
    value='1264193000',
    scheme='SCT',
    meaning='Local exogenous pigmentation of right buccal mucosa',
)

PIGMENTATION_MUCOSA_SOFT_PALATE = DicomCode(
    value='1260043007',
    scheme='SCT',
    meaning='Local exogenous pigmentation of mucosa of soft palate',
)

PIGMENTATION_MUCOSA_LIP_LOWER = DicomCode(
    value='1260047008',
    scheme='SCT',
    meaning='Local exogenous pigmentation of mucous membrane of lower lip',
)

PIGMENTATION_MUCOSA_LIP_UPPPER = DicomCode(
    value='1260049006',
    scheme='SCT',
    meaning='Local exogenous pigmentation of mucous membrane of upper lip',
)

OBSERVABLE_ENTITY = DicomCode(
    value='363787002',
    scheme='SCT',
    meaning='Observable entity',
)

PALSY = DicomCode(
    value='193093009',
    scheme='SCT',
    meaning="Bell's palsy (disorder)",
)

TONGUE_THRUST = DicomCode(
    value='110343009',
    scheme='SCT',
    meaning='Tongue thrust (observable entity)',
)

DENTAL_OCCLUSION = DicomCode(
    value='25272006',
    scheme='SCT',
    meaning='Dental occlusion, function',
)

CO = DicomCode(
    value='110320000',
    scheme='SCT',
    meaning='Centric occlusion (observable entity)',
)

CR = DicomCode(
    value='736783005',
    scheme='SCT',
    meaning='Centric relation (observable entity)',
)

DIRECT = DicomCode(
    value='255589003',
    scheme='SCT',
    meaning='Direct (qualifier value)',
)

TEMPORAL_EVENT_TYPE = DicomCode(
    value='128741',
    scheme='DCM',
    meaning='Longitudinal Temporal Event Type',
)

PATIENT_REGISTRATION = DicomCode(
    value='184047000',
    scheme='SCT',
    meaning='Patient registration (procedure)',
)

ORTHODONTIC_TREATMENT = DicomCode(
    value='122452007',
    scheme='SCT',
    meaning='Comprehensive orthodontic treatment (procedure)',
)

POSTTREATMENT = DicomCode(
    value='126074',
    scheme='DCM',
    meaning='Posttreatment',
)

OFFSET_FROM_EVENT = DicomCode(
    value='128740',
    scheme='DCM',
    meaning='Longitudinal Temporal Offset from Event',
)

DAY = DicomCode(
    value='d',
    scheme='UCUM',
    meaning='day',
)

RIGHT = DicomCode(
    value='24028007',
    scheme='SCT',
    meaning='Right (qualifier value)',
)

LEFT = DicomCode(
    value='7771000',
    scheme='SCT',
    meaning='Left (qualifier value)',
)

MOUTH = DicomCode(
    value='123851003',
    scheme='SCT',
    meaning='Mouth region structure (body structure)',
)

HEAD_NECK = DicomCode(
    value='774007',
    scheme='SCT',
    meaning='Structure of head and/or neck (body structure)',
)

DEVICE_PERIODONTAL_PROBE = DicomCode(
    value='462735007',
    scheme='SCT',
    meaning='Periodontal probe (physical object)',
)

DEVICE_MIRROR = DicomCode(
    value='47162009',
    scheme='SCT',
    meaning='Mirror, device (physical object)',
)

DEVICE_TONGUE_DEPRESSOR = DicomCode(
    value='39802000',
    scheme='SCT',
    meaning='Tongue blade, device (physical object)',
)

DEVICE_RULER = DicomCode(
    value='102304005',
    scheme='SCT',
    meaning='Measuring ruler, device (physical object)',
)

LATERALITY_BOTH = DicomCode(
    value='B',
    scheme='CS',
    meaning='Both',
)

LATERALITY_LEFT = DicomCode(
    value='L',
    scheme='CS',
    meaning='Left',
)

LATERALITY_RIGHT = DicomCode(
    value='R',
    scheme='CS',
    meaning='Right',
)

LATERALITY_UNPAIRED = DicomCode(
    value='U',
    scheme='CS',
    meaning='Unpaired',
)

ORIENTATION_LEFT = DicomCode(
    value='P^F',
    scheme='CS',
    meaning='Posterior, Foot',
)

ORIENTATION_RIGHT = DicomCode(
    value='A^F',
    scheme='CS',
    meaning='Anterior, Foot',
)

ORIENTATION_SUPINE_HEAD_TO_FEET = DicomCode(
    value='R^P',
    scheme='CS',
    meaning='Right, Posterior',
)

ORIENTATION_PRONE_FEET_TO_HEAD = DicomCode(
    value='R^A',
    scheme='CS',
    meaning='Right, Anterior',
)

ORIENTATION_FRONT = DicomCode(
    value='L^F',
    scheme='CS',
    meaning='Left, Foot',
)

ORIENTATION_BACK = DicomCode(
    value='R^F',
    scheme='CS',
    meaning='Right, Foot',
)

ORIENTATION_SUPINE_FEET_TO_HEAD = DicomCode(
    value='L^P',
    scheme='CS',
    meaning='Left, Posterior',
)

ORIENTATION_PRONE_HEAD_TO_FEET = DicomCode(
    value='L^A',
    scheme='CS',
    meaning='Left, Anterior',
)

DENTAL_ARCH_MANDIBULAR = DicomCode(
    value='88176008',
    scheme='SCT',
    meaning='Lower dental arch structure (body structure)',
)

DENTAL_ARCH_MAXILLARY = DicomCode(
    value='39481002',
    scheme='SCT',
    meaning='Upper dental arch structure (body structure)',
)

STRUCTURE_OF_BUCCAL_SPACE = DicomCode(
    value='261063000',
    scheme='SCT',
    meaning='Structure of buccal space (body structure)',
)

FRENUM = DicomCode(
    value='7652006',
    scheme='SCT',
    meaning='Structure of frenulum labii (body structure)',
)

FACE_STRUCTURE = DicomCode(
    value='89545001',
    scheme='SCT',
    meaning='Face structure (body structure)',
)

ORAL_CAVITY_STRUCTURE = DicomCode(
    value='74262004',
    scheme='SCT',
    meaning='Oral cavity structure (body structure)',
)

PROJECTION_FRONTAL = DicomCode(
    value='399033003',
    scheme='SCT',
    meaning='Frontal projection (qualifier value)',
)

PROJECTION_LEFT = DicomCode(
    value='399173006',
    scheme='SCT',
    meaning='Left lateral projection (qualifier value)',
)

PROJECTION_LEFT_OBLIQUE = DicomCode(
    value='260421001',
    scheme='SCT',
    meaning='Left lateral oblique (qualifier value)',
)

PROJECTION_RIGHT = DicomCode(
    value='399198007',
    scheme='SCT',
    meaning='Right lateral projection (qualifier value)',
)

PROJECTION_RIGHT_OBLIQUE = DicomCode(
    value='260424009',
    scheme='SCT',
    meaning='Right lateral oblique (qualifier value)',
)

PROJECTION_OBLIQUE = DicomCode(
    value='399182000',
    scheme='SCT',
    meaning='Oblique projection (qualifier value)',
)

PROJECTION_45DEG = DicomCode(
    value='260454004',
    scheme='SCT',
    meaning='45 degree projection (qualifier value)',
)

PROJECTION_OCCLUSAL = DicomCode(
    value='260499007',
    scheme='SCT',
    meaning='Occlusal projection (qualifier value)',
)

PROJECTION_SUBMENTOVERTICAL = DicomCode(
    value='399255003',
    scheme='SCT',
    meaning='Submentovertical projection (qualifier value)',
)

PROJECTION_VERTEX = DicomCode(
    value='260461000',
    scheme='SCT',
    meaning='Vertex projection (qualifier value)',
)

IMAGE_MIRRORED_UNCORRECTED = DicomCode(
    value='789135000',
    scheme='SCT',
    meaning='Mirrored visible image uncorrected (record artifact)',
)

IMAGE_MIRRORED_UNCORRECTED_FLIPPED_HORIZONTALLY = DicomCode(
    value='789134001',
    scheme='SCT',
    meaning='Mirrored visible image uncorrected flipped horizontally',
)

IMAGE_MIRRORED_UNCORRECTED_FLIPPED_HORIZONTALLY_VERTICALLY = DicomCode(
    value='789132002',
    scheme='SCT',
    meaning='Mirrored visible image uncorrected flipped horizontally and vert',
)

IMAGE_MIRRORED_UNCORRECTED_FLIPPED_VERTICALLY = DicomCode(
    value='789133007',
    scheme='SCT',
    meaning='Mirrored visible image uncorrected flipped vertically',
)

CLOSEUP = DicomCode(
    value='789131009',
    scheme='SCT',
    meaning='Close up photographic view of teeth with no set magnification or',
)

IMAGE_MIRRORED_CORRECTED = DicomCode(
    value='787610003',
    scheme='SCT',
    meaning='Photographic image corrected intraoral mirrored visible record (',
)

IMAGE_MIRRORED_CORRECTED_FLIPPED_HORIZONTALLY = DicomCode(
    value='789310004',
    scheme='SCT',
    meaning='Mirrored photographic image of teeth corrected flipped horizonta',
)

IMAGE_MIRRORED_CORRECTED_FLIPPED_VERTICALLY = DicomCode(
    value='789311000',
    scheme='SCT',
    meaning='Mirrored photographic image of teeth corrected flipped verticall',
)

IMAGE_MIRRORED_CORRECTED_FLIPPED_HORIZONTALLY_VERTICALLY = DicomCode(
    value='789312007',
    scheme='SCT',
    meaning='Mirrored photographic image of teeth corrected flipped verticall',
)

IMAGE_EXTRAORAL_45DEG = DicomCode(
    value='787612006',
    scheme='SCT',
    meaning='Photographic image extraoral with 45 degree view',
)

IMAGE_EXTRAORAL_MPF = DicomCode(
    value='787611004',
    scheme='SCT',
    meaning='Photographic image extraoral with mandible postured forward',
)

IMAGE_ANTERIOR_TEETH = DicomCode(
    value='789313002',
    scheme='SCT',
    meaning='Photographic image of anterior teeth',
)

IMAGE_FACE_LIPS_RELAXED = DicomCode(
    value='789314008',
    scheme='SCT',
    meaning='Photographic image of face with lips in relaxed position',
)

IMAGE_LIPS_CLOSED = DicomCode(
    value='787607005',
    scheme='SCT',
    meaning='Photographic image with lips closed',
)

IMAGE_MOUTH_PARTIALLY_OPEN_TEETH_APART = DicomCode(
    value='789130005',
    scheme='SCT',
    meaning='Photographic image with mouth partially opened position and teet',
)

RIGHT_AND_LEFT = DicomCode(
    value='51440002',
    scheme='SCT',
    meaning='Right And Left',
)

HEAD_NECK = DicomCode(
    value='774007',
    scheme='SCT',
    meaning='Structure of head and/or neck (body structure)',
)

FACE_LATERAL = DicomCode(
    value='422624005',
    scheme='SCT',
    meaning='Structure of half of face lateral to midsagittal plane (body str',
)

MAXILLA = DicomCode(
    value='70925003',
    scheme='SCT',
    meaning='Bone structure of maxilla (body structure)',
)

MANDIBLE = DicomCode(
    value='91609006',
    scheme='SCT',
    meaning='Bone structure of mandible (body structure)',
)

JAW = DicomCode(
    value='661005',
    scheme='SCT',
    meaning='Jaw region structure (body structure)',
)

SAGITTAL = DicomCode(
    value='30730003',
    scheme='SCT',
    meaning='Sagittal (qualifier value)',
)

INDIRECT = DicomCode(
    value='255541007',
    scheme='SCT',
    meaning='Indirect (qualifier value)',
)

INF_VIEW = DicomCode(
    value='261089000',
    scheme='SCT',
    meaning='Inferior (qualifier value)',
)

SUP_VIEW = DicomCode(
    value='264217000',
    scheme='SCT',
    meaning='Superior (qualifier value)',
)

EDENTULOUS = DicomCode(
    value='278650002',
    scheme='SCT',
    meaning='Edentulous (finding)',
)


# -----------------------------------------------------------------------
# CODES — keyword → DicomCode lookup (mirrors codes.csv)
# -----------------------------------------------------------------------

CODES: dict[str, DicomCode] = {
    'FunctionalConditionPresentDuringAcquisition': FUNCTIONAL_CONDITION_PRESENT_DURING_ACQUISITION,
    'OrthognathicFunctionalConditions': ORTHOGNATHIC_FUNCTIONAL_CONDITIONS,
    'mouth_open': MOUTH_OPEN,
    'mouth_partially_open': MOUTH_PARTIALLY_OPEN,
    'lips_relaxed': LIPS_RELAXED,
    'lips_closed': LIPS_CLOSED,
    'mpf': MPF,
    'smile': SMILE,
    'FindingByInspection': FINDING_BY_INSPECTION,
    'skin_mark': SKIN_MARK,
    'slap_mark': SLAP_MARK,
    'birthmark': BIRTHMARK,
    'tattoo': TATTOO,
    'gingival_recession': GINGIVAL_RECESSION,
    'cant': CANT,
    'pigmentation_mucosa_left': PIGMENTATION_MUCOSA_LEFT,
    'pigmentation_mucosa_right': PIGMENTATION_MUCOSA_RIGHT,
    'pigmentation_mucosa_soft_palate': PIGMENTATION_MUCOSA_SOFT_PALATE,
    'pigmentation_mucosa_lip_lower': PIGMENTATION_MUCOSA_LIP_LOWER,
    'pigmentation_mucosa_lip_uppper': PIGMENTATION_MUCOSA_LIP_UPPPER,
    'ObservableEntity': OBSERVABLE_ENTITY,
    'palsy': PALSY,
    'tongue_thrust': TONGUE_THRUST,
    'DentalOcclusion': DENTAL_OCCLUSION,
    'co': CO,
    'cr': CR,
    'direct': DIRECT,
    'TemporalEventType': TEMPORAL_EVENT_TYPE,
    'PatientRegistration': PATIENT_REGISTRATION,
    'OrthodonticTreatment': ORTHODONTIC_TREATMENT,
    'Posttreatment': POSTTREATMENT,
    'OffsetFromEvent': OFFSET_FROM_EVENT,
    'day': DAY,
    'right': RIGHT,
    'left': LEFT,
    'Mouth': MOUTH,
    'HeadNeck': HEAD_NECK,
    'device_periodontal_probe': DEVICE_PERIODONTAL_PROBE,
    'device_mirror': DEVICE_MIRROR,
    'device_tongue_depressor': DEVICE_TONGUE_DEPRESSOR,
    'device_ruler': DEVICE_RULER,
    'LateralityBoth': LATERALITY_BOTH,
    'LateralityLeft': LATERALITY_LEFT,
    'LateralityRight': LATERALITY_RIGHT,
    'LateralityUnpaired': LATERALITY_UNPAIRED,
    'OrientationLeft': ORIENTATION_LEFT,
    'OrientationRight': ORIENTATION_RIGHT,
    'OrientationSupineHeadToFeet': ORIENTATION_SUPINE_HEAD_TO_FEET,
    'OrientationProneFeetToHead': ORIENTATION_PRONE_FEET_TO_HEAD,
    'OrientationFront': ORIENTATION_FRONT,
    'OrientationBack': ORIENTATION_BACK,
    'OrientationSupineFeetToHead': ORIENTATION_SUPINE_FEET_TO_HEAD,
    'OrientationProneHeadToFeet': ORIENTATION_PRONE_HEAD_TO_FEET,
    'dental_arch_mandibular': DENTAL_ARCH_MANDIBULAR,
    'dental_arch_maxillary': DENTAL_ARCH_MAXILLARY,
    'StructureOfBuccalSpace': STRUCTURE_OF_BUCCAL_SPACE,
    'frenum': FRENUM,
    'FaceStructure': FACE_STRUCTURE,
    'OralCavityStructure': ORAL_CAVITY_STRUCTURE,
    'projection_frontal': PROJECTION_FRONTAL,
    'projection_left': PROJECTION_LEFT,
    'projection_left_oblique': PROJECTION_LEFT_OBLIQUE,
    'projection_right': PROJECTION_RIGHT,
    'projection_right_oblique': PROJECTION_RIGHT_OBLIQUE,
    'projection_oblique': PROJECTION_OBLIQUE,
    'projection_45deg': PROJECTION_45DEG,
    'projection_occlusal': PROJECTION_OCCLUSAL,
    'projection_submentovertical': PROJECTION_SUBMENTOVERTICAL,
    'projection_vertex': PROJECTION_VERTEX,
    'image_mirrored_uncorrected': IMAGE_MIRRORED_UNCORRECTED,
    'image_mirrored_uncorrected_flipped_horizontally': IMAGE_MIRRORED_UNCORRECTED_FLIPPED_HORIZONTALLY,
    'image_mirrored_uncorrected_flipped_horizontally_vertically': IMAGE_MIRRORED_UNCORRECTED_FLIPPED_HORIZONTALLY_VERTICALLY,
    'image_mirrored_uncorrected_flipped_vertically': IMAGE_MIRRORED_UNCORRECTED_FLIPPED_VERTICALLY,
    'closeup': CLOSEUP,
    'image_mirrored_corrected': IMAGE_MIRRORED_CORRECTED,
    'image_mirrored_corrected_flipped_horizontally': IMAGE_MIRRORED_CORRECTED_FLIPPED_HORIZONTALLY,
    'image_mirrored_corrected_flipped_vertically': IMAGE_MIRRORED_CORRECTED_FLIPPED_VERTICALLY,
    'image_mirrored_corrected_flipped_horizontally_vertically': IMAGE_MIRRORED_CORRECTED_FLIPPED_HORIZONTALLY_VERTICALLY,
    'image_extraoral_45deg': IMAGE_EXTRAORAL_45DEG,
    'image_extraoral_mpf': IMAGE_EXTRAORAL_MPF,
    'image_anterior_teeth': IMAGE_ANTERIOR_TEETH,
    'image_face_lips_relaxed': IMAGE_FACE_LIPS_RELAXED,
    'image_lips_closed': IMAGE_LIPS_CLOSED,
    'image_mouth_partially_open_teeth_apart': IMAGE_MOUTH_PARTIALLY_OPEN_TEETH_APART,
    'right_and_left': RIGHT_AND_LEFT,
    'head_neck': HEAD_NECK,
    'face_lateral': FACE_LATERAL,
    'maxilla': MAXILLA,
    'mandible': MANDIBLE,
    'jaw': JAW,
    'sagittal': SAGITTAL,
    'indirect': INDIRECT,
    'inf_view': INF_VIEW,
    'sup_view': SUP_VIEW,
    'edentulous': EDENTULOUS,
}


# -----------------------------------------------------------------------
# VIEWS — all orthodontic views from views.csv
# -----------------------------------------------------------------------

VIEWS: dict[str, OrthoView] = {
    'IV01': OrthoView(
        keyword='IV01',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Right Buccal Segment, Centric Occlusion, Direct View',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV02': OrthoView(
        keyword='IV02',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Right Buccal Segment - Centric Occlusion, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV03': OrthoView(
        keyword='IV03',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Right Buccal Segment - Centric Occlusion, With Mirror But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV04': OrthoView(
        keyword='IV04',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Right Buccal Segment - Centric Relation, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV05': OrthoView(
        keyword='IV05',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Right Buccal Segment - Centric Relation, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV06': OrthoView(
        keyword='IV06',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Right Buccal Segment - Centric Relation, With Mirror But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV07': OrthoView(
        keyword='IV07',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Frontal View - Centric Occlusion, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV08': OrthoView(
        keyword='IV08',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Frontal View - Centric Relation, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV09': OrthoView(
        keyword='IV09',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(IMAGE_MOUTH_PARTIALLY_OPEN_TEETH_APART,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral Frontal View - Teeth Apart, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV10': OrthoView(
        keyword='IV10',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral Frontal View - Mouth Open, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV11': OrthoView(
        keyword='IV11',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Frontal View Inferior (showing depth of bite and overjet) - Centric Occlusion, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV12': OrthoView(
        keyword='IV12',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Frontal View Inferior (showing depth of bite and overjet) - Centric Relation, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV13': OrthoView(
        keyword='IV13',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(TONGUE_THRUST,),
        dental_occlusion=CO,
        description='Intraoral Frontal View, showing Tongue Thrust, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV14': OrthoView(
        keyword='IV14',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(DEVICE_RULER,),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Right Lateral View - Centric Occlusion, Showing Overjet, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV15': OrthoView(
        keyword='IV15',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=RIGHT,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Right Lateral View - Centric Relation, Showing Overjet, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV16': OrthoView(
        keyword='IV16',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Left Lateral View - Centric Occlusion, Showing Overjet, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV17': OrthoView(
        keyword='IV17',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Left Lateral View - Centric Relation, Showing Overjet, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV18': OrthoView(
        keyword='IV18',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Left Buccal Segment - Centric Occlusion, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV19': OrthoView(
        keyword='IV19',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_LEFT,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Intraoral Left Buccal Segment - Centric Occlusion, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV20': OrthoView(
        keyword='IV20',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_LEFT,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Left Buccal Segment - Centric Occlusion, With Mirror But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV21': OrthoView(
        keyword='IV21',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Left Buccal Segment - Centric Relation, Without Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV22': OrthoView(
        keyword='IV22',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_LEFT,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Left Buccal Segment - Centric Relation, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV23': OrthoView(
        keyword='IV23',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=STRUCTURE_OF_BUCCAL_SPACE,
        primary_anatomic_structure_modifier=LEFT,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_LEFT,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Intraoral Left Buccal Segment - Centric Relation, With Mirror But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV24': OrthoView(
        keyword='IV24',
        patient_orientation=('R', 'A'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=DENTAL_ARCH_MAXILLARY,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_OCCLUSAL,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral Maxillary Occlusal View - Mouth Open, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV25': OrthoView(
        keyword='IV25',
        patient_orientation=('L', 'P'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=DENTAL_ARCH_MAXILLARY,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_OCCLUSAL,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral Maxillary Occlusal View - Mouth Open, With Mirror But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV26': OrthoView(
        keyword='IV26',
        patient_orientation=('L', 'P'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=DENTAL_ARCH_MANDIBULAR,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_OCCLUSAL,
        view_modifiers=(IMAGE_MIRRORED_UNCORRECTED,),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral Mandibular Occlusal View - Mouth Open, With Mirror',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV27': OrthoView(
        keyword='IV27',
        patient_orientation=('L', 'A'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=DENTAL_ARCH_MANDIBULAR,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_MIRROR,),
        view_code=PROJECTION_OCCLUSAL,
        view_modifiers=(IMAGE_MIRRORED_CORRECTED,),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral Mandibular Occlusal View - Mouth Open, With Mirror But Corrected',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV28': OrthoView(
        keyword='IV28',
        patient_orientation=None,
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=None,
        view_modifiers=(CLOSEUP,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(GINGIVAL_RECESSION,),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral - showing Gingival Recession (ISO tooth numbers)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV29': OrthoView(
        keyword='IV29',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FRENUM,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=None,
        view_modifiers=(CLOSEUP,),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral - showing Frenum (ISO tooth numbers)',
        series_description='Orthodontic Intraoral Series',
    ),

    'IV30': OrthoView(
        keyword='IV30',
        patient_orientation=None,
        image_laterality='U',
        anatomic_region=MOUTH,
        anatomic_region_modifier=None,
        primary_anatomic_structure=ORAL_CAVITY_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_PERIODONTAL_PROBE,),
        view_code=None,
        view_modifiers=(),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Intraoral - any photo using a photo accessory device such as a contraster to provide a solid background or black mirror ([modifier] is any set of IO modifier as specified above)',
        series_description='Orthodontic Intraoral Series',
    ),

    'EV01': OrthoView(
        keyword='EV01',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Right Profile (subject is facing observer's right) - Lips Relaxed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV02': OrthoView(
        keyword='EV02',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Right Profile (subject is facing observer's right) - Lips Relaxed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV03': OrthoView(
        keyword='EV03',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Right Profile (subject is facing observer's right) - Lips Closed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV04': OrthoView(
        keyword='EV04',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Right Profile (subject is facing observer's right) - Lips Closed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV05': OrthoView(
        keyword='EV05',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Right profile (subject is facing observer's right) - Full Smile, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV06': OrthoView(
        keyword='EV06',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Right Profile (subject is facing observer's right) - Full Smile, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV07': OrthoView(
        keyword='EV07',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_RIGHT,
        view_modifiers=(),
        orthognathic_functional_conditions=(MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="Right Profile (subject is facing observer's right) - Mandible Postured Forward",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV08': OrthoView(
        keyword='EV08',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="45° Right Profile (subject turns toward observer's right) - Lips Relaxed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV09': OrthoView(
        keyword='EV09',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="45° Right Profile (subject turns toward observer's right) - Lips Relaxed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV10': OrthoView(
        keyword='EV10',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="45° Right Profile (subject turns toward observer's right) - Lips Closed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV11': OrthoView(
        keyword='EV11',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="45° Right Profile (subject turns toward observer's right) - Lips Closed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV12': OrthoView(
        keyword='EV12',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="45° Right Profile (subject turns toward observer's right) - Full Smile, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV13': OrthoView(
        keyword='EV13',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="45° Right Profile (subject turns toward observer's right) - Full Smile, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV14': OrthoView(
        keyword='EV14',
        patient_orientation=('A', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=RIGHT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="45° Right Profile (subject turns toward observer's right) - Mandible Postured Forward",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV15': OrthoView(
        keyword='EV15',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Full Face - Lips Relaxed, Centric Occlusion',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV16': OrthoView(
        keyword='EV16',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Full Face - Lips Relaxed, Centric Relation',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV17': OrthoView(
        keyword='EV17',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Full Face - Lips Closed, Centric Occlusion',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV18': OrthoView(
        keyword='EV18',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Full Face - Lips Closed, Centric Relation',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV19': OrthoView(
        keyword='EV19',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description='Full Face - Full Smile, Centric Occlusion',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV20': OrthoView(
        keyword='EV20',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Full Face - Full Smile, Centric Relation',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV21': OrthoView(
        keyword='EV21',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Full Face - Mandible Postured Forward',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV22': OrthoView(
        keyword='EV22',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Left Profile (subject is facing observer's left) - Lips Relaxed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV23': OrthoView(
        keyword='EV23',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Left Profile (subject is facing observer's left) - Lips Relaxed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV24': OrthoView(
        keyword='EV24',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Left Profile (subject is facing observer's left) - Lips Closed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV25': OrthoView(
        keyword='EV25',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Left Profile (subject is facing observer's left) - Lips Closed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV26': OrthoView(
        keyword='EV26',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="Left profile (subject is facing observer's left) - Full Smile, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV27': OrthoView(
        keyword='EV27',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="Left Profile (subject is facing observer's left) - Full Smile, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV28': OrthoView(
        keyword='EV28',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="Left Profile (subject is facing observer's left) - Mandible Postured Forward",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV29': OrthoView(
        keyword='EV29',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="45° Left Profile (subject turns toward observer's left) - Lips Relaxed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV30': OrthoView(
        keyword='EV30',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="45° Left Profile (subject turns toward observer's left) - Lips Relaxed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV31': OrthoView(
        keyword='EV31',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="45° Left Profile (subject turns toward observer's left) - Lips Closed, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV32': OrthoView(
        keyword='EV32',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_CLOSED,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="45° Left Profile (subject turns toward observer's left) - Lips Closed, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV33': OrthoView(
        keyword='EV33',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CO,
        description="45° Left Profile (subject turns toward observer's left) - Full Smile, Centric Occlusion",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV34': OrthoView(
        keyword='EV34',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description="45° Left Profile (subject turns toward observer's left) - Full Smile, Centric Relation",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV35': OrthoView(
        keyword='EV35',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=LEFT,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_45DEG,
        view_modifiers=(),
        orthognathic_functional_conditions=(SMILE, MPF,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description="45° Left Profile (subject turns toward observer's left- Full Smile, Mandible Postured Forward",
        series_description='Orthodontic Extraoral Series',
    ),

    'EV36': OrthoView(
        keyword='EV36',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_SUBMENTOVERTICAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Other Face (head tipped back) - Inferior View (showing lower border of mandible, nares, infraorbital rim contours, forehead contours)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV37': OrthoView(
        keyword='EV37',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_VERTEX,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Other Face (viewed from a bove) - Superior View (showing forehead, infraorbital rim contour, dorsum of nose, upper lip, chin)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV38': OrthoView(
        keyword='EV38',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(CLOSEUP,),
        orthognathic_functional_conditions=(SMILE,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=CR,
        description='Other Face - Close-Up Smile (with lips)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV39': OrthoView(
        keyword='EV39',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(DEVICE_TONGUE_DEPRESSOR,),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(LIPS_RELAXED,),
        findings_by_inspection=(CANT,),
        observable_entities=(),
        dental_occlusion=None,
        description='Other Face - Occlusal Cant ( e.g., tongue depressor)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV40': OrthoView(
        keyword='EV40',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=None,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Other Face - Forensic Interest (tattoos, jewelry, scars)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV41': OrthoView(
        keyword='EV41',
        patient_orientation=('P', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_LEFT,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Other Face - Anomalies (ears, skin tags, etc.)',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV42': OrthoView(
        keyword='EV42',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(MOUTH_OPEN,),
        findings_by_inspection=(),
        observable_entities=(),
        dental_occlusion=None,
        description='Full Face - Mouth Open',
        series_description='Orthodontic Extraoral Series',
    ),

    'EV43': OrthoView(
        keyword='EV43',
        patient_orientation=('L', 'F'),
        image_laterality='U',
        anatomic_region=HEAD_NECK,
        anatomic_region_modifier=None,
        primary_anatomic_structure=FACE_STRUCTURE,
        primary_anatomic_structure_modifier=None,
        devices=(),
        view_code=PROJECTION_FRONTAL,
        view_modifiers=(),
        orthognathic_functional_conditions=(),
        findings_by_inspection=(),
        observable_entities=(PALSY,),
        dental_occlusion=None,
        description='Full Face - demonstrating Nerve Weakness',
        series_description='Orthodontic Extraoral Series',
    ),

}
